apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-slack-webhooks
  namespace: monitoring
type: Opaque
stringData:
  slack-default-url: "https://hooks.slack.com/services/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"
  slack-security-url: "https://hooks.slack.com/services/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"
