apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: ExternalName
  externalName: market-kafka-kafka-bootstrap.kafka.svc.cluster.local
  ports:
    - port: 9092
      protocol: TCP
