apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inventory-reserve-request-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: market-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    min.insync.replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: inventory-reserved-result-topic
  namespace: kafka
  labels:
    strimzi.io/cluster: market-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 604800000
    min.insync.replicas: 1
