global:
  defaultStorageClass: "ebs-sc"
  security:
    allowInsecureImages: true

kafka:
  image:
    registry: public.ecr.aws
    repository: bitnami/kafka
    tag: 3.9.0-debian-12-r3
    pullPolicy: Always

  defaultInitContainers:
    volumePermissions:
      enabled: true
      image:
        registry: public.ecr.aws
        repository: bitnami/os-shell
        tag: 12-debian-12-r51
      containerSecurityContext:
        runAsUser: 0

  persistence:
    enabled: true
    storageClass: "ebs-sc"
    size: 2Gi

  listeners:
    client:
      containerPort: 9092
      protocol: PLAINTEXT
    controller:
      containerPort: 9093
      protocol: PLAINTEXT
    interbroker:
      containerPort: 9094
      protocol: PLAINTEXT
    # 다른 네임스페이스(default)의 서비스가 찾아올 수 있도록 전체 DNS 주소 광고
    advertisedListeners: 'PLAINTEXT://$(KAFKA_POD_NAME).kafka-controller-headless.kafka.svc.cluster.local:9092'

  extraConfig: |
    listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
    inter.broker.listener.name=INTERNAL
