apiVersion: v2
name: istio-ingressgateway
description: Istio ingress gateway
type: application
version: 1.0.0
dependencies:
  - name: gateway
    version: 1.23.*
    repository: https://istio-release.storage.googleapis.com/charts
