kube-prometheus-stack:
  grafana:
    adminPassword: admin1234

    grafana.ini:
      server:
        root_url: "%(protocol)s://%(domain)s/grafana"
        serve_from_sub_path: true

    ingress:
      enabled: true
      ingressClassName: traefik
      path: /grafana
      pathType: Prefix
      hosts:
        - ""

    additionalDataSources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '\[[\w.-]+,([a-f0-9]{16,32}),'
              url: '$${__value.raw}'
              datasourceUid: tempo
              urlDisplayLabel: View Trace in Tempo
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo.monitoring.svc.cluster.local:3200
        access: proxy
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            spanStartTimeShift: '-1m'
            spanEndTimeShift: '1m'
            tags:
              - key: service.name
                value: app
            filterByTraceID: true
            filterBySpanID: false
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true

    persistence:
      enabled: true
      storageClassName: ebs-sc
      size: 5Gi

  prometheus:
    prometheusSpec:
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      podMonitorNamespaceSelector: {}
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: ebs-sc
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi

  alertmanager:
    enabled: false

  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true
