apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rate-limit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/kjylab/ktcloud-k8s-argocd-manifest.git'
    targetRevision: HEAD
    path: Addons/TraefikMiddleware
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
