traefik:
  service:
    enabled: true
    type: NodePort

  ingressClass:
    enabled: true
    isDefaultClass: true

  providers:
    kubernetesIngress:
      publishedService:
        enabled: true

  ports:
    web:
      exposedPort: 80
      nodePort: 31896
    websecure:
      exposedPort: 443
      nodePort: 31897
