service:
  enabled: true
  type: LoadBalancer  # ✅ AWS LoadBalancer를 생성하도록 설정
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443
