service:
  enabled: true
  type: LoadBalancer  # ✅ AWS LoadBalancer를 생성하도록 설정
  annotations:
    # AWS NLB를 생성하고 싶다면 아래 주석을 켭니다 (권장)
    service.beta.kubernetes.io/aws-load-balancer-type: nlb

ingressClass:
  enabled: true
  isDefaultClass: true

ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443
