apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-slack-webhooks
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: alertmanager-slack-webhooks
    creationPolicy: Owner
    template:
      data:
        slack-default-url: "{{ .defaultUrl }}"
        slack-security-url: "{{ .securityUrl }}"
  data:
    - secretKey: defaultUrl
      remoteRef:
        key: troica/slack/webhooks
        property: default-url
    - secretKey: securityUrl
      remoteRef:
        key: troica/slack/webhooks
        property: security-url
