apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-app
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - path: Addons/Postgresql
        name: postgresql
        destNamespace: postgresql
      - path: Addons/Redis
        name: redis
        destNamespace: redis
      - path: Addons/Kafka
        name: kafka
        destNamespace: kafka
      - path: Addons/EbsCsi
        name: ebs-csi
        destNamespace: kube-system
      - path: Addons/Prometheus
        name: prometheus
        destNamespace: monitoring
      - path: Addons/Loki
        name: loki
        destNamespace: monitoring
      - path: Addons/Tempo
        name: tempo
        destNamespace: monitoring
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/kjylab/ktcloud-k8s-argocd-manifest.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{destNamespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true