apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - list:
      elements:
      - path: Apps/msa-market
        name: msa-market
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/kjylab/ktcloud-k8s-argocd-manifest'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
