apiVersion: v2
name: redis-addon
description: Market Service용 Redis Cluster 차트
type: application
version: 1.0.0
appVersion: "8.6.3"

dependencies:
  - name: redis
    version: 25.5.2
    repository: https://charts.bitnami.com/bitnami
