apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: auth-service
  password: auth-service
---
apiVersion: v1
kind: Secret
metadata:
  name: order-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: order-service
  password: order-service
---
apiVersion: v1
kind: Secret
metadata:
  name: inventory-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: inventory-service
  password: inventory-service
---
apiVersion: v1
kind: Secret
metadata:
  name: product-db-credentials
  namespace: postgresql
type: kubernetes.io/basic-auth
stringData:
  username: product-service
  password: product-service
